import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true, //* will prepare the font before viewing the page.
});
export const metadata: Metadata = {
  title: "Food Ordering Application",
  description: "Generated by Next.JS and Tailwind CSS and Shadcnui and Prisma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
